


tests/fwrisc_decode_formal_smoke.f
tests/fwrisc_mul_div_shift_formal_sra.f
tests/fwrisc_mul_div_shift_formal_srl.f
tests/fwrisc_mul_div_shift_formal_mul.f
tests/fwrisc_mul_div_shift_formal_mulh.f
tests/fwrisc_mul_div_shift_formal_muls.f
tests/fwrisc_mul_div_shift_formal_mulsh.f
